# nvrs
# https://github.com/adamperkowski/nvrs

[__config__]
oldver = "vold.json"
newver = "vnew.json"
keyfile = "keyfile.toml"

[hyprgui]
source = "github"
github = "hyprutils/hyprgui"
prefix = "v"

[hyprlauncher]
source = "github"
github = "hyprutils/hyprlauncher"
prefix = "v"

[hyprwall]
source = "github"
github = "hyprutils/hyprwall"
prefix = "v"

[linutil]
source = "github"
github = "christitustech/linutil"
prefix = "v"

[permitter]
source = "github"
github = "adamperkowski/permitter"
prefix = "v"

[smriti]
source = "github"
github = "aspasht/smriti"
prefix = "v"

[amdgpud]
source = "github"
github = "eraden/amdgpud"
prefix = "v"

[quarantine]
source = "github"
github = "zahash/quarantine"
prefix = "v"

[youtube-tui-nodefaults-bin]
source = "github"
github = "Siriusmart/youtube-tui"
prefix = "v"

[nvrs]
source = "github"
github = "adamperkowski/nvrs"
prefix = "v"

[rawbit]
source = "github"
github = "cartercanedy/rawbit"
prefix = "v"

[protondb-cli]
source = "github"
github = "hypeedev/protondb-cli"
prefix = "v"

[transgender]
source = "github"
github = "Sberm/Transgender.rs"

[ntfy]
source = "github"
github = "dschep/ntfy"
prefix = "v"
use_max_tag = true

[jqp]
source = "github"
github = "noahgorstein/jqp"
prefix = "v"

[codesnap]
source = "github"
github = "mistricky/CodeSnap"
prefix = "v"

[arv]
source = "github"
github = "tranzystorekk/arrive"
prefix = "v"

[hyprpolkitagent]
source = "github"
github = "hyprwm/hyprpolkitagent"
prefix = "v"

[doccli]
source = "github"
github = "TowarzyszFatCat/doccli"
prefix = "v"

[rustcraft]
source = "github"
github = "c2i-junia/rustcraft"
prefix = "v"

[display3d]
source = "github"
github = "renpenguin/display3d"
prefix = "v"
use_max_tag = true

[gh-skyline]
source = "github"
github = "github/gh-skyline"
prefix = "v"
