# nvrs
# https://github.com/adamperkowski/nvrs

[__config__]
oldver = "vold.json"
newver = "vnew.json"
keyfile = "keyfile.toml"

[linutil]
source = "github"
github = "christitustech/linutil"
prefix = "v"

[permitter]
source = "github"
github = "adamperkowski/permitter"
prefix = "v"

[smriti]
source = "github"
github = "aspasht/smriti"
prefix = "v"

[amdgpud]
source = "github"
github = "eraden/amdgpud"
prefix = "v"

[quarantine]
source = "github"
github = "zahash/quarantine"
prefix = "v"

[youtube-tui-nodefaults-bin]
source = "github"
github = "Siriusmart/youtube-tui"
prefix = "v"

[nvrs]
source = "github"
github = "adamperkowski/nvrs"
prefix = "v"

[rawbit]
source = "github"
github = "cartercanedy/rawbit"
prefix = "v"

[protondb-cli]
source = "github"
github = "hypeedev/protondb-cli"
prefix = "v"

[transgender]
source = "github"
github = "Sberm/Transgender.rs"

[ntfy]
source = "github"
github = "dschep/ntfy"
prefix = "v"
use_max_tag = true

[jqp]
source = "github"
github = "noahgorstein/jqp"
prefix = "v"

[codesnap]
source = "github"
github = "mistricky/CodeSnap"
prefix = "v"

[arv]
source = "github"
github = "tranzystorekk/arrive"
prefix = "v"

[hyprpolkitagent]
source = "github"
github = "hyprwm/hyprpolkitagent"
prefix = "v"

[doccli]
source = "github"
github = "TowarzyszFatCat/doccli"
prefix = "v"

[rustcraft]
source = "github"
github = "c2i-junia/rustcraft"
prefix = "v"

[display3d]
source = "github"
github = "renpenguin/display3d"
prefix = "v"
use_max_tag = true

[gh-skyline]
source = "github"
github = "github/gh-skyline"
prefix = "v"

[jellyfin-tui]
source = "github"
github = "dhonus/jellyfin-tui"
prefix = "v"

[julec]
source = "github"
github = "julelang/jule"
prefix = "jule"

[envfetch]
source = "github"
github = "ankddev/envfetch"
prefix = "v"

[ad]
source = "github"
github = "sminez/ad"

[tuistash]
source = "github"
github = "edmocosta/tuistash"
prefix = "v"

[omu]
source = "github"
github = "utox39/oh-my-update"
prefix = "v"

[mult]
source = "github"
github = "dhth/mult"
prefix = "v"

[fancy-cat]
source = "github"
github = "freref/fancy-cat"
prefix = "v"
use_max_tag = true

[comlink]
source = "github"
github = "rockorager/comlink"
prefix = "v"

[tek]
source = "gitea"
host = "codeberg.org"
gitea = "unspeaker/tek"

[sisyphus]
source = "github"
github = "hachiya-kurisu/sisyphus"
prefix = "v"
use_max_tag = true

[gengou]
source = "github"
github = "hachiya-kurisu/gengou"
prefix = "v"
use_max_tag = true

[kri]
source = "github"
github = "ikozyris/kri"
prefix = "v"

[lnx]
source = "github"
github = "lnx-search/lnx"
prefix = "v"

[nsv]
source = "github"
github = "purpleclay/nsv"
prefix = "v"

[cloudip]
source = "github"
github = "jongwoo328/cloudip"
prefix = "v"
use_max_tag = true

[goskyr]
source = "github"
github = "jakopako/goskyr"
prefix = "v"

[libxpm]
source = "regex"
url = "https://xorg.freedesktop.org/releases/individual/lib/?C=M;O=D"
encoding = "utf8"
regex = 'libXpm-([\d.]+).tar.gz'

[brlcad]
source = "github"
github = "BRL-CAD/brlcad"
prefix = "rel-"

[cvm]
source = "github"
github = "number571/cvm"
prefix = "v"
use_max_tag = true

[awtfdb]
source = "github"
github = "lun-4/awtfdb"

[auth]
source = "github"
github = "nnyyxxxx/auth"
prefix = "v"

[jed]
source = "regex"
url = "https://jedsoft.org/jed/index.html"
encoding = "utf8"
regex = 'Version ([\d.-]+)'

[arnis]
source = "github"
github = "louis-e/arnis"
prefix = "v"

[fireworkrs]
source = "github"
github = "crisidev/fireworkrs"
prefix = "v"
use_max_tag = true

[eddy]
source = "github"
github = "70sh1/eddy"
prefix = "v"

[katharsis]
source = "github"
github = "kurosakishigure/katharsis"
prefix = "v"
use_max_tag = true

[fetchfetch]
source = "github"
github = "spenserblack/fetchfetch"
prefix = "v"
use_max_tag = true

[hyprland-qt-support]
source = "github"
github = "hyprwm/hyprland-qt-support"
prefix = "v"
